// GENERATED by scripts/build-terms.mts from tyme4ts. Do not edit; run `npm run gen:terms`.
// 4152 solar terms from 1928-12-22T02:03:36.000Z; format in termCodec.ts.

import type { TermTableData } from './termCodec'

export const TERM_DATA: TermTableData = {
  firstYear: 1929,
  yearSeconds: 31556925,
  anchor: [
    -1294696584,
    -1293424679,
    -1292152670,
    -1290876677,
    -1289595192,
    -1288304883,
    -1287005115,
    -1285693727,
    -1284371385,
    -1283037580,
    -1281694347,
    -1280342953,
    -1278986367,
    -1277627302,
    -1276268806,
    -1274914279,
    -1273565928,
    -1272226826,
    -1270897665,
    -1269580378,
    -1268273916,
    -1266978753,
    -1265692317,
    -1264413816,
  ],
  years: [
    'gUYSh5aDj8cHl0dkmVeClVemjPfVf6fkckgDbMhlcEjwdxlI', // 1930
    'eLkCcCguYQdAUjarSLaPRlbSTWdVXSfNbfgIeugmgsg2hYg1', // 1931
    'hNgrghf9fYekepdUfjdAiTdZldeEnaeTmwdEjlaafrXoc6WC', // 1932
    'cMWMdVXvfPZwgubthYeAhXgzgajFeukpdkldcwlKbwkRa6ju', // 1933
    'a1kGbvlQc1lzcVkJZkgOWBblUJX7UwWDXgWlblY1ffbSiDc5', // 1934
    'i_dTihcjhebZhBaVhIZBhHYBhLY2h6bti_fPj-h0j5h9iJfm', // 1935
    'fAb1bfYWYzWzX4YKYvb_aQgUbSjxcbmNd7nSfGnggIn2g1oG', // 1936
    'gxn2f_nEfAmJeklhfXlAg6jLhhe8gSZ1esWreXWYfvYYiibm', // 1937
    'l2evocgopfgloseomYcFkAbYirc5hUesfQgAd8hpelkDgymh', // 1938
    'i0nejBmTg5jcc3gAYLdUUhcgT5eWXZh5c1k0hJmDjImCjdl5', // 1939
    'jlmokWn1lWoemGn5mmmFnJjbnvg4oKfVoFekm6dOkca3hmYm', // 1940
    'gBYBgxZ3jqdhnZhgqHkhqWmBnol6jIlSfoldehmofKoAgHoy', // 1941
    'gopDhCpdhkp3hapif8nvdSkSalf9Y-b9ZCZ-bRbFfSebjlh8', // 1942
    'mQjjmPilkagZjDerjbd6lGd1m3ebn2ffnkgQmIgCkGe7iMde', // 1943
    'gwb8ffaeePZndZabdrdxfQi_hIn7iaq4iiq7hFo5fAmvdflr', // 1944
    'dImCd7nOfFoQf5ofgVnngplag9h3gxdngFaOfcYLe9XXfAX0', // 1945
    'gCZkiGcCkmeCmSeJmIcZkoa5jUblisd7iKghh9iviMj9iLjj', // 1946
    'g8hMeSd3a-a5X0ZTVNZLTOaJSpcfVIgfaQklfUnRiSn8icmz', // 1947
    'gpk0ePiucQhIbogbc7gff2gWi0e_kTc5khbfkDamjKZ1iSZJ', // 1948
    'hpYqhVYkhkZGiZaPjcb4kCd5jOfagZf6dIgZbsh5cfkNemmm', // 1949
    'g1oSiKoohlm9ecjiZifaUgbuRgZZRdYCTFXVVrYYZdbgd2fj', // 1950
    'hmiujejrjMiVhufegMcFfiZPgDYVh3Z6j7cCkRcPiYagf1YZ', // 1951
    'eGXOdvXTeZYZfUaDf1cRfufFfBh6eLkeeFmXeMm1dll1cEkO', // 1952
    'asjUajj-b8l_eLoRf_o8gNmleuhbcMbNaBW4Z4V7bnXOd2ZJ', // 1953
    'fma2g6cTiUdhj4d9lGdTlecQlCbzjzcAh2cngkeQhQg0jKil', // 1954
    'j5huh8eSd2aEZYXZWNXnU8aPVSeFXbiFaok2dElteFleeElM', // 1955
    'd8lUd1lOdTkdcqjcdCjDfgjZjZjKmNhVmsehlHbUiZYggOXL', // 1956
    'f2X7heaVkUdHm_e_oefroigLnihVlzi6jwkOiHlAhClCgZkx', // 1957
    'gWk2hDldhnlogjkfdNh7YYezUacvTtcmWReBaagZefi7hRkm', // 1958
    'iNk5hij-gWiyf9h0gsgviMfLj4d2l2eRoTgUqKhzqPhVoefA', // 1959
    'lhbsiTYuf_XWfcYSgnbaiefyjijyjDmfiAoLhlpeh-qhiiq_', // 1960
    'iqqsiLp4hVpMgppNgapWgBoJfIk3dkf2brbZbKZ8c_btgjfd', // 1961
    'kgjXnilxoyltoKjKmdfflLcuk8cBlRc0k4djjxeUjpf-lFh4', // 1962
    'mnilmxhjk7e_hTb8c6aIZUayXud7Y-izchnRfjpAgEoIe1mw', // 1963
    'eBmtejn6f-pdhWqQiIpritoAjylZkfh4kfe7kKcvi7aagwYO', // 1964
    'e-XcfHY6hqcKlxfqpihqq_hipggemRfuiufrgig0geihhajg', // 1965
    'h_jah7ixhKh2fdg9c6gJZfe2VodETIb3TJbuVKdDYlf-ccjQ', // 1966
    'fEk6fKkAdShrbbffbMeXdSeEgrdvjqdWlldIlwb_j-ZzhgXi', // 1967
    'fcVyd_UldCT7cuUPdbWQfRaahmflipjXhmkpfckLdRi9boh6', // 1968
    'bDhxbnikcuj0dek5dLk7bbjbZchFYgeSYQbkYeZ8ZLZuaMaq', // 1969
    'bfcWdEeNepfMfieQfYbje8Yfe8W3f_XzhsaHjJcXkLdykbdc', // 1970
    'jCbCgHXicoUUZeSbXISgVnUpU7YXVydhZEjWdUnxgJphgnpC', // 1971
    'fgnfdvlrb_kTa6j1a3kBcBkHd_i1fGfkfGcZfMayfmaZgAan', // 1972
    'gPbEgcbig9cDiIcij3cslPcWlTb_kBb2hlb1foc9f9fiiaiw', // 1973
    'lrlfoLmsoPlZlHiOfxe0Z4cUVBbUSxb5TUdHVTevYOhfb-lJ', // 1974
    'fioShtpuiHpUhMnRfokSe9hhgEflipfCl0fgnhewmQcJjSZP', // 1975
    'g0XrgHYDhZZ-j8ccmjekoHgbodihndkblhlyj-myjDmxh5lq', // 1976
    'gwkogik4hpm2jqp4lLsDkPrTgwnxcri8Zqe0YxdUaRemc-hE', // 1977
    'fVjMgxkfhrk9iakjjXjjlBiLmogUnXexnTeGm-eVnRffoUgb', // 1978
    'ogfomwc0jTZKfoWgdQWhc3Zxd_e_flkMhIoEiFpvh0pZgtoe', // 1979
    'gDoDf8n5fsnmfEngeroBffpMh-p6kaoUk2kpjVgbg3c5eobC', // 1980
    'dubUesdWhLf5kIhfmpheoGgKoXfPobf6oPg9nShdmKhblchL', // 1981
    'lWhIlyhQlwgqkAe-gLcrbDa1WOaWTvcHVCfxYvjocdmcetnl', // 1982
    'e9m6delJbmjpahixaVh_bIhAdJf5f_fLjTfnmRgKnRfZl5dC', // 1983
    'i1Z0fZW5dGVadCV4fQX5iRaikgdUlAfjjsg-iXimidkTjVlS', // 1984
    'j4lJjikCiPixgniWe_iqcyiaZkgsWJdyTmayStZpUQbgX7fl', // 1985
    'cXj8f6muhVmmgNjjdxfXcfb-dRZ1fQZDhRZTigZ3jWa7khcG', // 1986
    'lWcdlGbhjdZMggV8c3TGZxSuYjV1ZWbMbmgtdzj6eEj2ciiX', // 1987
    'bUhpbdiQcpj6eAlzemm7eCmudNlKciiJbtevbJcVa1a2aPZ7', // 1988
    'ZsaEaVb3c2e7g3h9lEjPnnhfnQd6lSbMjQaBh6aciJcIjpd4', // 1989
    'lCeqldeOkecpiHape7ZObaY0XlYyUFZXSvbKT7d5WrhJZ9kM', // 1990
    'celwc_lTb2j8aUi1ZiiiaejCdcjig1iyjFhEjoepiVb3gFZh', // 1991
    'eCYLc3XscpXsdjYNfxZei9blmMenoYhUn-iGljhhjAgbhRff', // 1992
    'gyfThfgHivhjjmjGjLkCgyj5dDi2ZrhtX_gqXjf0X0fyYvg0', // 1993
    'aOircGkud3mBetlgeWjZeIg2fHerhWdzkaernegSpghOpugT', // 1994
    'nqdZkCZmgVWRd1UVc8UBdKVjeNZVf7etiMkakuoymVqimQp9', // 1995
    'k_oFjGl6hKkif4k2frmygKo-glpngRn0fTkyedileiiFfUi0', // 1996
    'gVkAhMk-h5lXirlKj7kXlqizm_gmnfe0nIdzmgd3m2fYo0h_', // 1997
    'rokot4lytvkHqbf8k1bTe4YmaRYxXvbHXkedZHhubZkseCne', // 1998
    'gopniYqujAq-iZqPggoheWmkd8ldf_lLjMk_lPjnkmgrhxdT', // 1999
    'esbIdJa8d3cdgoeskdgZnugqpPgMpOgIoJgam3hDmFhYlZgy', // 2000
    'klf1kOfsk5g_mUjbnKljlrl4hLjxbIglWgeYU4eLWDgDY3i6', // 2001
    'bnlJdKmHddl8c2k2cGjfcZiSeEgsf4eUhBcWiCb0jQcckPc0', // 2002
    'j3bwhtY-eSVSbOSXZ_Raa6TEdfXTggcfiTgbihiWhxidg0iC', // 2003
    'gph9g-iAg9h5gHh9e8jCeKk-dymcdcmJckjsaogAYJc1WObX', // 2004
    'Vvb9XDeMZpgvcTiFeNhhfffZgfcxhsbUjPbUkUbjkebckRbT', // 2005
    'kTbhkrbxkkbFjLY9gDVwbsTOXkTAU_VZVHaAX-fYbrjceKlD', // 2006
    'ehkMc_iDa9giZjgXYxg8YLhQYVhcaHhnc1hnfLhRgLgZfben', // 2007
    'dJcLaVZ3YYYkYmY8bmapgMcLj6cklhcalMcKkPcokOd8lWfg', // 2008
    'mwghnjgnnVf-mNfOkQevhberdkeDYpceUXbESRbBS8dJWJhH', // 2009
    'aplietougupef1nec2kLaXhfaigJc-fRfqebhmd0irdpjDdk', // 2010
    'ivdRh9ckg5bMfyZMe9XCenV3fYXchvb2kogwmajomGjdkOhw', // 2011
    'iqghiZgrjTiLkpkllinPlQpNjVpWgSn2dnlqb4joa2iIZ-hH', // 2012
    'ZRg6ZkiIbjkve1nliUpIk6oIl_k0l9hAlvemmAeKnBfPoqgz', // 2013
    'p_hsqHhColewmBbwjSY_gvXieoX9c2Zxb0coccgPemjyhPmY', // 2014
    'jEnIjCmChdkXfVjedtkJdLl_eEoMgUpjiZo0iimKg3jAedgf', // 2015
    'cafKbbe7befMcifre6ggiyhfnEiNqVisrrimrHhtpdgTn1fF', // 2016
    'nBetnRfUoTgZpGg_oSgYlWfZhJescoeXZbe4YagBY2hTZ6in', // 2017
    'bWj_c5lVeFmTeNmTc_lPbRjkawiScfhyfpiLjXjlmjk3nnkP', // 2018
    'lrhYhrdSdYZSamWkaXVZcCVQeWWjhOaEkZejm3iEoFjqoKjm', // 2019
    'neiPl9gNkBediReEhXf2hTjDgnk2d3kFaiiPYQgzXnguYkiH', // 2020
    'agkTcqmUeVnlfKntfNmnfJknfwiIgwfGhNcZhkbWircXk6e7', // 2021
    'nthxp2jCpqhOmxcmiCWpc8R6ZYQzYWTRY8XNaRbAcEeGeIgZ', // 2022
    'gIh6hli1iXjgiHj1gij0d9jjbhjrbCkscmlUdqkFcmhQZ2eC', // 2023
    'W_cCVxcFWyd6ZqgcdliahgiokKglk6dykscIkrb6k4cAkxbr', // 2024
    'kObAjxa8kVcEl7dunBefl_eBiXcbcgZ-WrYYTtY_UMbjW7e5', // 2025
    'aJhicTivc1ixcBifauimZxi4Z5jBbNiPcdgidVfXeYfUfFfO', // 2026
    'egeLcZbtZQYUWmVeWZUfZMVadvX5ipbmmVejnQfIlyd5j4co', // 2027
    'i_cMjKcajkctjfdCi8eXiqhXiRkOgjlUeAkpbMigYTf8WFeX', // 2028
    'VeenWzgxZlj1cUmJdmmZdek5dsjIfZhsh0g7kKg0lngtl3gW', // 2029
    'lWf6kefAjEdIhTaQfNWbctSraoRVabTrcSYrfregjejBmDkw', // 2030
    'mUjmkhhCiFfEgGeue9gJeMiTdRkVdCmbeToEfroZgHnrfTmH', // 2031
    'dXj9a8hzZDgbYsgbajhzecjUitjGlMg_l4fDmbexnjf4pPhm', // 2032
    'q7jDr8josCjKrVhsplfOmyc7jabmfXapbFaGYhbHZFeLceir', // 2033
    'hPnLlaqJnKqllooxhvmOdWkNaqjtbHkUdWkkfNkJgGjmgCi8', // 2034
    'fTiTeUhkdYgecse8cudOd8bsgMbHjYctnMfyp-huqShXo6f-', // 2035
    'nnfInjfpo0hXqsjcr_lWr6m-ptnKk6lffhjhb5iZaTh8Zxhq', // 2036
    'ZshsaUixcIlRexoehBqohuqahXoShHlBg1hug-gGiKgokFiX', // 2037
    'lwjvl-jMkMgghhc4fgZbemWqeVVXepWMfZYegYbUh7eKj7gU', // 2038
    'ldhDlsgXkke5iedugdeVfdhDfVklfjnifzodetmhb6jFYnf9', // 2039
    'WLeVVXeXWAffXgg8ZfiTcXjkgNkEjqjBljhPmKfjlld0kTce', // 2040
    'jTcCjScukbd_l-ecmNcpkGZbgrXGdUWhalXTZWZJZ4bXbWdM', // 2041
    'c7eXeIfBeifRd5fWcWfnaEfuXygCXdhSZhi-cdkke6lcfYkZ', // 2042
    'dMhYZQdWVMZpSoXcS0XFV1XvaMYWegZpiwcNmRefoBfeoZfb', // 2043
    'n6eimqdAlEbajyaejUbAjwdUjxfZhFfLcZdxYqdEXUdmYCfL', // 2044
    'aBhMcTjEd9kaeclIdkk-bqkAaajMbDiKcBgLclesdpfLf0hh', // 2045
    'inkckmlqkPjxhafAdgY6aKTVYgQgZlR4c1VzgCZeiJb3jddL', // 2046
    'kVdylBeTlpe1lrfCkkfKigf5gGhYeKjkdwlvdymHchkJZrg7', // 2047
    'WpeZVKeCWDgHY6jpcamyfcoKhnnHikkAiuhIjlgTlFgumGhA', // 2048
    'l5gilBf-kugClrgUm1fbmlc5kVZsglW6cWVZZqWMaHZRdOdQ', // 2049
    'hFgbjohmj1hAiGgHf_gleZiOdLkEcllfc0mAdWmBeCmIeamB', // 2050
    'd8lNcdjXaBgjXbd2WXcnYWdUdGe5iqgjnQhypehdo8fvnTeO', // 2051
    'mRdxmReOm9e1npe-n_e_oRf_oQhrmsigjWh9flgkcifDaveO', // 2052
    'ase5cghPfjkriYn4jWpZhto2fOn4esnggAnPhwnBjHnDjynJ', // 2053
    'jvm8i0lvg2jQebf1cUb0bAXpaqUpb9U8ffYrkKdkoShTqoin', // 2054
    'qjhcosfMmkdWlFcokbdbkNfrjsihiek_hSmxgfnkfwnOepl7', // 2055
    'dGkFbdibaQh0aFi0bIlCdKnNfon2hXl4hoi0h3hOjFhuk_jd', // 2056
    'm1lRn-mMoLlvnnjomQf6kRbhh-X4fvVydZUybWVCbOXSd2bS', // 2057
    'iUfwmqjDo4j4n0idkUgkgEftcdgUasibbSk2cml7c2lPboje', // 2058
    'ZxhxYRgpXagFXGfuXOfRYRe2a0eoeceyigf0l-gmnKfzmBd5', // 2059
    'j_cLiqbwjEc0lIepn0gFpiggpAftlud0glblcKagaPazaSbg', // 2060
    'bDcGcAdAdWe4fEhxgYkogCl7d-lscGkobJi_ayhvbYiGdBj0', // 2061
    'evlKe4kRckg8Y8ciWCYrVcWDXAUXZhUIcqVzfzYNiPaSj7bo', // 2062
    'kwcCkubqkDamiyZLhgYnhCabhqeZiQiRhpkGfmjYccgxY9dr', // 2063
    'WUblVXbPV7ceXReyYnhYZyjkbUlEdelJfLj0gFiLgNgwfrfz', // 2064
    'fAfje0gEfig8gwgxhNeQgNZueMVMchTEcLTqc-V3euYrg_bK', // 2065
    'jCcukNdIkGcdisbXgka2eHbQbeciZje9Zzidb7lyeGnaeYmb', // 2066
    'cQjTYjfRUpb7R_aeRjbFTic6Xbemb2fcf_gNjphRmOiTnvjL', // 2067
    'oRjZnziym2hjmOgWmmfrn0fgocfCm2deiwbHeeZycpakdydA', // 2068
    'gxgGkIi2mbklm1lLlPlCiHkte1lAdHlvczlrclk3crk-eAm8', // 2069
    'glp1i7rdjPqahBmmdNhPZ7cMZBY1a7YWfMawj8dvm_fYoBfs', // 2070
    'n_fqoHgRpGhVqVh8q4hlqQhHo5h2nUjklmlEj4lgh6kIfFhN', // 2071
    'cDeZaXdlbBfodykEhTpIjrsaj9syi8quhwn6hRmJh1l_izmf', // 2072
    'jMmsi4mjitmljTmakMlAkwh2kLdHiMYof-WFeyV7fcYCiIbg', // 2073
    'lkekn5fyoBe6mXdSkdc1jNeYihhThpj_gjl1fxmwfGmcd1k8', // 2074
    'cDi3aBgkXvebVodUUrd7V4gQZrjhfEmAjrmfl5lIlri9kQhN', // 2075
    'i5gbiRgfihgwjVgjkhf8mEfLnHeSm_dmlXcjihbBfrZjd7Yx', // 2076
    'dtZIfCa1hSdXjQfqjfg4hXhLeEhnbti_bplEdCmueWnie9ns', // 2077
    'exnFdblKa1iKXmetUgbJShX_SoV3VFVmZyYQf8crlagWoQhe', // 2078
    'n4f-ladRisathAZCg3YchoY5idajiqcshleCf5eyeyfDeJen', // 2079
    'dedhcjcRbkbtbCcxbWfocFi7cTk2b3ksbNjMa4iBbniodnkx', // 2080
    'gDnNh5opicoRhSlbejghbwa-Z9V0ZBSHY1QeZGQhaKSTc1V3', // 2081
    'g6aOk_dsnYexnMdVkyanhUYveRZScYb0b5fRcoiEdAikbyg-', // 2082
    'Z0e5YTdlXrdgXrehX2f7X2g_YXh3aWimdQi-f7jBhbihhUhZ', // 2083
    'f9gGenfiejgFgOhVjRibmah5nce-ltbHiUXre1VtdDVydgXO', // 2084
    'fOZBhNa3jLc6k-fLl_hRldi7jSj2gIkEdZkGb6kMbxlAdAmt', // 2085
    'ezoFfSnUdQkWZeghVsdUTxbnUybUYAbjcAcdf_eAjDfYkngE', // 2086
    'k3gJklgBkRfZkBeRkOdPlRdSnKfNpPiApai_m5hmjHe1fjb-', // 2087
    'dSaVc4akeGchf_fjhljDiRmVh3oqhIp4hCqLhKpcguoMf1nJ', // 2088
    'fCmwe6nRfvoVgwoVgil-fHhpdscoc8YydsX1f7ZUitbplIdp', // 2089
    'mqeznNe9m3eOmMdOlucXlCb-j8c7i4faiei5jcmlk6olk2no', // 2090
    'inkOezfzascUXxbfXEdxYYhqarlNdfncgXoRinoXkLorlYpT', // 2091
    'l2pclSorj_nEixlUi1kKkvjSm1hOm-d7k8abiDYCgdX9hXaM', // 2092
    'kWdrn9g9qsi2rcivpyhOmagHjIg4g2ixfakceelQd7lxecnB', // 2093
    'gFoohdpHhCnxeYkuaAgnVfc1TWa-U-beZgdxe8ghi9iEkQh8', // 2094
    'jkhOizhMjGhtkWh_l6hWnBftnSeXnUeYm4euldehjkdXhSbF', // 2095
    'e0YpdMXmdWY6fPcWh3g9jrk8i-mbf0lqcrkgbKj6bGkOb-lJ', // 2096
    'c1l0dIl_dHl_c9lacKjjbDghaNcSZNXUYVT7Y1TmbFV5elZn', // 2097
    'iTdAkqeYksdJjDaphjYcgyXfgyYthIbNgsdQfneZeceLc1cn', // 2098
    'a9adZEYQXGWfVOWEUOX-Usb6WigjZpknc7mTeQlJdbjBcBhg', // 2099
    'bGhLbKh7cHi_dYjZemi7gOhghsesiHbchrY4gmW6fGVbd_U3', // 2100
    'd8VifNXbhiZ8j8bwkxbujJa4ggbReNdGdFgAdjjBevlCfhlm', // 2101
  ],
}
