#!/usr/bin/env node
// Generates src/lib/qimen/termData.ts, the solar-term table the Qimen engine reads at runtime
// (qimen-spec.md §4.3, §14.2). tyme4ts stays a dev dependency and the test oracle. Owner: qimen.
//
//   npm run gen:terms            write the table
//   node scripts/build-terms.mts --check   exit 1 if the committed table is stale
//
// tyme4ts JulianDay values are JD(UT) + 8 h; the conversion is calendar.md's tymeJdToDate,
// rounded to the second exactly as qimen-spec §14.2 does.

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { gzipSync } from 'node:zlib'
import { SolarTerm } from 'tyme4ts'
import { decodeTermSeconds, encodeTermTable, type TermTableData } from '../src/lib/qimen/termCodec.ts'

/** fromIndex(1929, 0) is 冬至 1928-12-22, 24 rows before 1930; the table ends with 大雪 2101. */
export const FIRST_YEAR = 1929
export const LAST_YEAR = 2101
export const YEAR_SECONDS = 31_556_925

export const OUT_PATH = fileURLToPath(new URL('../src/lib/qimen/termData.ts', import.meta.url))

/** Term starts in epoch seconds from tyme4ts, row 0 = 冬至 of December firstYear − 1. */
export function tymeTermSeconds(firstYear = FIRST_YEAR, lastYear = LAST_YEAR): number[] {
  const rows: number[] = []
  for (let y = firstYear; y <= lastYear; y++) {
    for (let k = 0; k < 24; k++) {
      const jd = SolarTerm.fromIndex(y, k).getJulianDay().getDay()
      rows.push(Math.round((jd - 2440587.5) * 86400 - 480 * 60))
    }
  }
  for (let i = 1; i < rows.length; i++) {
    if ((rows[i] as number) <= (rows[i - 1] as number)) throw new Error(`tyme4ts terms not increasing at row ${i}`)
  }
  return rows
}

export function renderTermModule(data: TermTableData): string {
  const first = new Date((data.anchor[0] as number) * 1000).toISOString()
  const years = data.years.map((line, k) => `    '${line}', // ${data.firstYear + 1 + k}`).join('\n')
  return `// GENERATED by scripts/build-terms.mts from tyme4ts. Do not edit; run \`npm run gen:terms\`.
// ${data.anchor.length + data.years.length * 24} solar terms from ${first}; format in termCodec.ts.

import type { TermTableData } from './termCodec'

export const TERM_DATA: TermTableData = {
  firstYear: ${data.firstYear},
  yearSeconds: ${data.yearSeconds},
  anchor: [
${data.anchor.map((s) => `    ${s},`).join('\n')}
  ],
  years: [
${years}
  ],
}
`
}

function main(): void {
  const seconds = tymeTermSeconds()
  const data = encodeTermTable(seconds, FIRST_YEAR, YEAR_SECONDS)
  const decoded = decodeTermSeconds(data)
  if (decoded.length !== seconds.length || decoded.some((s, i) => s !== seconds[i])) {
    throw new Error('term table does not round-trip')
  }
  const source = renderTermModule(data)
  if (process.argv.includes('--check')) {
    const current = readFileSync(OUT_PATH, 'utf8')
    if (current !== source) {
      console.error(`${OUT_PATH} is stale. Run npm run gen:terms.`)
      process.exit(1)
    }
    console.log('termData.ts is up to date')
    return
  }
  writeFileSync(OUT_PATH, source)
  const gz = gzipSync(source, { level: 9 }).length
  console.log(`wrote ${OUT_PATH}: ${seconds.length} rows, ${source.length} B, ${gz} B gzip`)
}

if (import.meta.main) main()
